### ISSUE TITLE
missing data and plots folders

### ISSUE THREAD

**Issue by cdkodira** [rsankowski/Taka_A1_A2_only#1]
data and plots folders are missing

**Comment by rsankowski** [comment]
Dear good point. I think at the point I was doing the analysis I had added them manually and dropped the data into the data folder. The plots folders should populated using the code. Hope this helps and sorry for any inconvenience!

**Comment by cdkodira** [comment]
I still don't see the data folder and also sigature genes used in 3_plotting.R
